/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef comProto_CONSTANTS_H
#define comProto_CONSTANTS_H

#include "comProto_types.h"

namespace comProto {

class comProtoConstants {
 public:
  comProtoConstants();

};

extern const comProtoConstants g_comProto_constants;

} // namespace

#endif
