/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "comProto_constants.h"

namespace comProto {

const comProtoConstants g_comProto_constants;

comProtoConstants::comProtoConstants() {
}

} // namespace

